services:
  identifier:
    image: semtech/mu-identifier:1.10.1
    environment:
      SESSION_COOKIE_SECURE: "on"
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"},{"variables":[],"name":"clean"}]'
    links:
      - dispatcher:dispatcher
    restart: always
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  database:
    image: semtech/mu-authorization:0.6.0-beta.5
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
  resource:
    image: semtech/mu-cl-resources:1.23.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    links:
      - database:database
    volumes:
      - ./config/resources:/config
    restart: always
  file:
    image: semtech/mu-file-service:feature-validate-readable-metadata
    links:
      - database:database
    volumes:
      - ./data/files:/share
    environment:
      VALIDATE_READABLE_METADATA: "true"
    restart: always
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
  deltanotifier:
    image: semtech/mu-delta-notifier:0.2.0
    volumes:
      - ./config/delta:/config
    restart: always
  accountdetail:
    image: lblod/account-detail-service:0.1.0
    links:
      - database:database
    restart: always
