services:
  identifier:
    ports:
      - "80:80"
  virtuoso:
    ports:
      - "8890:8890"
  mock-login:
    image: lblod/mock-login-service:latest
    links:
      - database:database
    restart: "no"
