steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    context: ./frontend-hackhathon
    settings:
      repo: frontend-hackathon-g1
      tags: latest
    secrets: [docker_username, docker_password]
when:
  branch: main
  event: push
